# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20170404_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='img/team/', verbose_name='\u0424\u043e\u0442\u043e min 320*320'),
        ),
    ]
