# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_auto_20170410_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='email',
            field=models.EmailField(max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='team',
            name='location',
            field=models.CharField(max_length=255, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
        migrations.AddField(
            model_name='team',
            name='phone',
            field=models.CharField(max_length=255, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d\u044b'),
        ),
    ]
