# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_auto_20170425_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='office_phone',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='\u041e\u0444\u0438\u0441\u043d\u044b\u0439 \u0442\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='team',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d\u044b'),
        ),
    ]
