# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_services_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='img/services/', verbose_name='\u0424\u043e\u0442\u043e 640*426'),
        ),
    ]
