# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_month8journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month8journal',
            name='worker',
        ),
        migrations.DeleteModel(
            name='Month8Journal',
        ),
    ]
